---
# tasks file for consul_base

- name: create consul install directory
  file:
    path: "{{ consul_install_dir }}"
    state: directory
    owner: root
    group: root

- name: unpack consul on machine
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: "{{ consul_install_dir }}"
    creates: "{{ consul_install_dir }}/consul"
    remote_src: yes 
    owner: root
    group: root


