---
# tasks file for consul


- name: Setup configuration directory
  file:
    state: directory
    path: "{{ consul_config_dir }}"
    owner: root
    group: root

- name: Setup data directory
  file:
    state: directory
    path: "{{ consul_data_dir }}"
    owner: root
    group: root

- name: update configuration file
  template:
    src: server.json.j2
    dest: "{{ consul_config_dir }}/server.json"
    owner: root
    group: root
  notify: reload consul service


- name: Setup systemd service definition
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
  notify: 
    - reload systemctl daemon
    - reload consul service

- name: Create consul service
  service:
    name: consul
    enabled: yes
  notify: reload consul service