---
# tasks file for common

- name: Set timezone to CET
  file: 
    src: /usr/share/zoneinfo/Europe/Amsterdam
    dest: /etc/localtime
    state: link
  when: ansible_distribution=="CentOS"

- name: Install required packages
  yum:
    name: "{{ required_packages }}"
    state: installed


